version: "3"
services:
  dev:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev
    environment:
      - NODE_ENV=development

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
